<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Template.Core.Domain\Template.Core.Domain.csproj" />
    <ProjectReference Include="..\Template.Core.Domain\Template.Core.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentNHibernate" Version="3.4.1" />
    <PackageReference Include="NHibernate" Version="5.4.9" />
    <PackageReference Include="Npgsql" Version="10.0.3" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>203541db-f161-4c27-9191-91bf18411825</UserSecretsId>
  </PropertyGroup>

</Project>
